### ISSUE TITLE
Cannot get property getCookie of null

### ISSUE THREAD

**Issue by javierojeda94** [vladotesanovic/ngx-slack#2]
I'm using Angular 5 and followed the direction on your npm package. 

Unfortunately, when I tested it, it showed up this error:

![image](https://user-images.githubusercontent.com/5795113/38387164-95bf13de-38dc-11e8-8193-d1d0fdeec5ec.png)

Can you help me to fix this? Probably it has something to do with Angular version or something else.

Cool package, by the way.

**Comment by ghost** [comment]
Same problem, is there a solution?

**Comment by javierojeda94** [comment]
It seems like they abandoned this repo... What a shame, it seemed to be a good project 

I think I'm closing this issue since it was never attended and it seems like they will never do it...
